
version: "2"

volumes:
    mongo-data:

services:
    nginx:
        image: nginx:latest
        container_name: filtercloud-nginx
        ports:
            - "8001:8001/tcp"
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
            - ./static:/www/data
        depends_on:
            - api
        environment:
            - VIRTUAL_HOST=filter.poe.gg
            - VIRTUAL_NETWORK=nginx-proxy
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=filter.poe.gg
            - LETSENCRYPT_EMAIL=benjaminschug@gmail.com

    api:
        build: .
        container_name: filtercloud-api
        command: bash -c "gunicorn -w 4 --forwarded-allow-ips='*' --proxy-allow-from='*' -b 0.0.0.0:8081 api.api:app"
        depends_on:
            - db
        links:
            - db
        volumes:
            - ./src:/src
            - ./templates:/templates
        expose:
            - "8081"

    db:
        image: mongo:3.6
        container_name: filtercloud-db
        volumes:
            - mongo-data:/data/db
        expose:
            - "27017"
