
version: "2"
services:
    nginx:
        image: nginx:latest
        container_name: nginx01
        ports:
            - "80:80"
        volumes:
            - ./config/nginx:/etc/nginx/conf.d
            - ./static:/www/data
        depends_on:
            - api

    api:
        build: .
        container_name: api01
        command: bash -c "gunicorn -w 4 --forwarded-allow-ips='*' -b 0.0.0.0:80 api.api:app"
        depends_on:
            - db
        volumes:
            - ./src:/src
            - ./templates:/templates
        expose:
            - "80"

    db:
        image: postgres:latest
        container_name: postgres01
